apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argo-cd
spec:
  project: cluster-addons
  syncPolicy:
    automated: {}
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    helm:
      valueFile: values.yaml
    path: cluster-addons/argo-events/
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: master