apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-of-apps
  namespace: argo-cd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: cluster-addons
  source:
    path: cluster-app-of-apps
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: master