apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=./dockerfile",
            "--context=git://sandile-yakka:sa11ndi%3Fle%23@github.com/InstaFinders/inventory-gatherer.git",
            "--destination=516599252282.dkr.ecr.af-south-1.amazonaws.com/inventory-gatherer:v1-kaniko"] 
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
  