apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-of-apps
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: cluster-addons
  source:
    path: argo-app-of-apps
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: master