apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ns-ecr-renew-demo
  name: svc-ecr-renew-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo-events
  name: cr-ecr-renew-demo
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argo-events
  name: rb-ecr-renew-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cr-ecr-renew-demo
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew-demo
    namespace: ns-ecr-renew-demo