apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kaniko-build-template
  namespace: argo-events
spec:
  templates:
  - name: build-dag
    dag:
      tasks:
      - name: build
        template: kaniko-build
      - name: deploy-to-dev
        template: deploy-to-dev
        dependencies:
          - build
  - name: kaniko-build
    inputs:
      parameters:
      - name: dockerfile_path
        value: './dockerfile'
      - name: branch
        value: master # default branch
      - name: repo_url
        value: 'git://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@github.com/InstaFinders/inventory-gatherer.git'
      - name: registry_url
        value: '516599252282.dkr.ecr.af-south-1.amazonaws.com/inventory-gatherer'
    serviceAccount: argo-workflow-executor-sa
    serviceAccountName: argo-workflow-executor-sa
    container:
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile={{inputs.parameters.dockerfile_path}}",
             "--context={{inputs.parameters.repo_url}}/{{inputs.parameters.branch}}",
             "--destination={{inputs.parameters.registry_url}}:{{inputs.parameters.branch}}"]
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker 
    volumes:
    - name: kaniko-secret
      secret:
        secretName: ecr-docker-login
        items:
          - key: .dockerconfigjson
            path: config.json
  - name: deploy-to-dev
    inputs:
      parameters:
      - name: argo_repo_url
        value: https://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@github.com/sandile-yakka/argo-cluster-addons.git#master # default branch
    script: 
      command: ['sh', '-c', 'wget https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64 -O /usr/bin/yq &&\
        chmod +x /usr/bin/yq;
        git clone {{inputs.parameters.argo_repo_url}}
        yq w -i ./dev/overlord-api/values.yaml image.tag {{inputs.parameters.branch}}
        git commit -m "Updates helm chart for overlord for branch {{inputs.parameters.branch}}" --all
        git push {{inputs.parameters.argo_repo_url}}
        ']
      image: node:14 
    serviceAccount: argo-workflow-executor-sa
    serviceAccountName: argo-workflow-executor-sa
  

