apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overlord-api-dev
  namespace: argo-cd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      valueFiles:
        - values.yaml
    path: dev-app-of-apps/
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: master
  sourceType: Helm