apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: kaniko-build
  generateName: kaniko-build
  namespace: argo-events
spec:
  entrypoint: kaniko-build-template
  workflowTemplateRef:
    name: kaniko-build-template