apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  name: ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo-events
  name: ecr-renew
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argo-events
  name: rb-ecr-renew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-renew
subjects:
  - kind: ServiceAccount
    name: ecr-renew
    namespace: argo-events