apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: cluster-addons
  source:
    path: argo/argo-events
    repoURL: https://github.com/sandile-yakka/argo-cluster-addons
    targetRevision: main